# Generated by Django 4.1.7 on 2023-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=20, verbose_name='Номер телефона')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сайт')),
                ('datatime', models.DateTimeField(verbose_name='Следующий звонок')),
                ('comment', models.TextField(max_length=1000, verbose_name='Комментарий')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
