# Generated by Django 4.1.7 on 2023-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datatime',
            field=models.DateField(verbose_name='Следующий звонок'),
        ),
    ]
