# Generated by Django 4.1.7 on 2023-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='number',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
